import { describe, test, expect } from 'bun:test';
import { getPathContext, applyContextFilter } from './context-filter.js';
import type { Finding } from '../types.js';

const base: Finding = {
  id: 'f1', severity: 'high', category: 'vulnerability',
  confidence: 80, rule_id: 'test.rule', message: 'test', location: {},
};

describe('getPathContext', () => {
  test('production file -> 1.0', () => {
    const ctx = getPathContext('src/app.ts');
    expect(ctx.context_multiplier).toBe(1.0);
    expect(ctx.is_test).toBe(false);
  });

  test('test file -> 0.3', () => {
    const ctx = getPathContext('tests/app.test.ts');
    expect(ctx.context_multiplier).toBe(0.3);
    expect(ctx.is_test).toBe(true);
  });

  test('node_modules -> 0.1', () => {
    const ctx = getPathContext('node_modules/lodash/index.js');
    expect(ctx.context_multiplier).toBe(0.1);
    expect(ctx.is_vendor).toBe(true);
  });

  test('@generated content -> 0.1', () => {
    const ctx = getPathContext('src/gen.ts', '// @generated by protoc');
    expect(ctx.context_multiplier).toBe(0.1);
    expect(ctx.is_generated).toBe(true);
  });

  test('.d.ts -> 0.1 (generated)', () => {
    const ctx = getPathContext('dist/index.d.ts');
    expect(ctx.context_multiplier).toBe(0.1);
    expect(ctx.is_generated).toBe(true);
  });
});

describe('applyContextFilter', () => {
  test('reduces confidence for test files (80 * 0.3 = 24)', () => {
    const ctx = getPathContext('tests/foo.test.ts');
    const result = applyContextFilter([{ ...base, confidence: 80 }], ctx);
    expect(result[0].confidence).toBe(24);
  });

  test('keeps finding in results even when confidence reduced', () => {
    const ctx = getPathContext('node_modules/pkg/index.js');
    const result = applyContextFilter([base], ctx);
    expect(result.length).toBe(1);
    expect(result[0].confidence).toBe(8);
  });

  test('sets path_context on findings', () => {
    const ctx = getPathContext('src/app.ts');
    const result = applyContextFilter([base], ctx);
    expect(result[0].path_context).toBeDefined();
    expect(result[0].path_context?.is_test).toBe(false);
  });
});
