import type { Finding, PathContext } from '../types.js';
import { CONTEXT_MULTIPLIERS } from '../constants.js';

const TEST_PATTERNS = [
  /\/tests?\//, /\/spec\//, /\/__tests__\//, /\/__mocks__\//,
  /\.test\.[jt]sx?$/, /\.spec\.[jt]sx?$/, /_test\.py$/, /_spec\.rb$/,
  /\/test_[^/]+\./,
];

const VENDOR_PATTERNS = [
  /(^|\/)node_modules\//, /(^|\/)vendor\//, /(^|\/)third_party\//,
  /\.min\.[jt]sx?$/, /\.min\.css$/,
];

const GENERATED_CONTENT = [
  /@generated/, /DO NOT EDIT/, /Code generated by/,
  /This file is auto-generated/, /\/\* eslint-disable \*\//,
];

const DOCS_PATTERNS = [/\/docs\//, /\/examples\//, /\.md$/, /\.txt$/, /\.rst$/];

export function getPathContext(filePath: string, firstLines?: string): PathContext {
  const is_test = TEST_PATTERNS.some(p => p.test(filePath));
  const is_vendor = VENDOR_PATTERNS.some(p => p.test(filePath));
  const is_generated = filePath.endsWith('.d.ts') ||
    (firstLines !== undefined && GENERATED_CONTENT.some(p => p.test(firstLines)));
  const is_docs = DOCS_PATTERNS.some(p => p.test(filePath));

  let context_multiplier: number;
  if (is_vendor || is_generated || is_docs) {
    context_multiplier = CONTEXT_MULTIPLIERS.vendor;
  } else if (is_test) {
    context_multiplier = CONTEXT_MULTIPLIERS.test;
  } else {
    context_multiplier = CONTEXT_MULTIPLIERS.production;
  }

  return { is_test, is_vendor, is_generated, is_docs, context_multiplier };
}

export function applyContextFilter(findings: Finding[], pathContext: PathContext): Finding[] {
  return findings.map(f => ({
    ...f,
    path_context: pathContext,
    confidence: Math.min(100, Math.max(0, Math.round(f.confidence * pathContext.context_multiplier))),
  }));
}
